services:
  question-service:
    image: golang:1.23.2
    command: ["go", "run", "./backend/cmd/question-service"]
    ports:
      - 3001:3001
    depends_on:
      - question-service-db
  question-service-db:
    image: mongodb/mongodb-community-server:8.0.1-ubuntu2204
    ports:
      - 27017:27017
  game-service:
    image: golang:1.23.2
    command: ["go", "run", "./backend/cmd/game-service"]
    ports:
      - 3002:3002
    depends_on:
      - game-service-db
  game-service-db:
    image: mongodb/mongodb-community-server:8.0.1-ubuntu2204
    ports:
      - 27018:27017
