services:
  question-service:
    build:
      context: ./
      dockerfile: ./backend/cmd/question-service/Dockerfile
    command: ['-mongoURI=mongodb://question-service-db:27017']
    ports:
      - 3001:3001
    depends_on:
      - question-service-db
  question-service-db:
    image: mongodb/mongodb-community-server:8.0.1-ubuntu2204
    ports:
      - 27017:27017
    volumes:
      - question-service-db-volume:/data/db
  game-service:
    build:
      context: ./
      dockerfile: ./backend/cmd/game-service/Dockerfile
    command: ['-mongoURI=mongodb://game-service-db:27017']
    ports:
      - 3002:3002
    depends_on:
      - game-service-db
  game-service-db:
    image: mongodb/mongodb-community-server:8.0.1-ubuntu2204
    ports:
      - 27018:27017
    volumes:
      - game-service-db-volume:/data/db
  user-service:
    build:
      context: ./
      dockerfile: ./backend/cmd/user-service/Dockerfile
    command: ['-mongoURI=mongodb://user-service-db:27017']
    ports:
      - 3004:3004
    environment:
      - ACCESS_TOKEN_PRIVATE_KEY=${ACCESS_TOKEN_PRIVATE_KEY}
      - REFRESH_TOKEN_KEY=${REFRESH_TOKEN_KEY}
    depends_on:
      - user-service-db
  user-service-db:
    image: mongodb/mongodb-community-server:8.0.1-ubuntu2204
    ports:
      - 27019:27017
    volumes:
      - user-service-db-volume:/data/db
  bff:
    build:
      context: ./
      dockerfile: ./bff/Dockerfile
    ports:
      - 3003:3003
    environment:
      - QUESTION_SERVICE_URL=question-service:3001
      - GAME_SERVICE_URL=game-service:3002
      - USER_SERVICE_URL=user-service:3004
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - COOKIE_KEY=${COOKIE_KEY}
volumes:
  question-service-db-volume:
  game-service-db-volume:
  user-service-db-volume:
