services:
  question-service:
    build:
      context: ./
      dockerfile: ./backend/cmd/question-service/Dockerfile
    command: ["-mongoURI=mongodb://question-service-db:27017"]
    ports:
      - 3001:3001
    depends_on:
      - question-service-db
  question-service-db:
    image: mongodb/mongodb-community-server:8.0.1-ubuntu2204
    ports:
      - 27017:27017
    volumes:
      - question-service-db-volume:/data/db
  game-service:
    build:
      context: ./
      dockerfile: ./backend/cmd/game-service/Dockerfile
    command: ["-mongoURI=mongodb://game-service-db:27017"]
    ports:
      - 3002:3002
    depends_on:
      - game-service-db
  game-service-db:
    image: mongodb/mongodb-community-server:8.0.1-ubuntu2204
    ports:
      - 27018:27017
    volumes:
      - game-service-db-volume:/data/db
  bff:
    build:
      context: ./
      dockerfile: ./bff/Dockerfile
    ports:
      - 3003:3003
    environment:
      - QUESTION_SERVICE_URL=question-service:3001
      - GAME_SERVICE_URL=game-service:3002
volumes:
  question-service-db-volume:
  game-service-db-volume:
